BERT_TOKENIZER: "SZTAKI-HLT/hubert-base-cc"
BERT_MODEL: "SZTAKI-HLT/hubert-base-cc"
BERT_MODEL_OUTPUT_HIDDEN_STATES: True
BERT_TOKENIZER_DO_LOWERCASE: False
BERT_TOKENIZER_MAX_LENGTH: 20
CNN_KERNEL_SIZE: 3
CNN_DILATIONS: [1,2,3]
LSTM_N_FILTERS: 16
LSTM_HIDDEN_DIM: 32
LSTM_N_LAYERS: 1
LSTM_BATCH_FIRST: True
LSTM_BIDIRECTIONAL: True
LINEAR_OUTPUT_DIM: 3
DROPOUT: 0.2
LEARNING_RATE: 0.0001
LEARNING_RATE_SCHEDULER_GAMMA: 0.9
EPOCH: 1
BATCH_SIZE: 32