data_preprocess:
  test_size: 0.2
  val_size: 0.1
  random_seed: 42

model:
  cnn_kernel_size: 3
  cnn_dilations: [1,2,3]
  lstm_n_filters: 16
  lstm_hidden_dim: 32
  lstm_n_layers: 1
  lstm_bidirectional: True
  linear_output_dim: 3
  dropout: 0.2

training:
  learning_rate: 0.001
  learning_rate_gamma_value: 0.9
  early_stopping_patience: 4
  epoch: 1
  batch_size: 16
  random_seed: 42

evaluation:
  batch_size: 16
  random_seed: 42