from .stage_00_data_ingestion import DataIngestionTrainingPipeline
from .stage_01_data_preparation import DataPreprocessTrainingPipeline
from .stage_02_prepare_base_model import PrepareBaseModelTrainingPipeline
from .stage_03_train_model import TrainingPipeline
from .stage_04_evaluation import EvaluationPipeline